import type { Metadata } from "next";
import { AppShell } from "@/components/sirt/AppShell";

export const metadata: Metadata = {
  title: "Terms of Service — S.I.R.T.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-2">
      <p className="font-mono text-xs text-muted-ash uppercase tracking-widest border-b border-grid-line pb-1">
        {title}
      </p>
      <div className="text-sm text-muted-ash leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <AppShell>
      <div className="flex-1 px-6 py-10 w-full max-w-2xl mx-auto">
        {/* Header */}
        <div className="mb-10">
          <p className="text-[11px] font-mono text-muted-ash uppercase tracking-widest mb-2">
            S.I.R.T.
          </p>
          <h1 className="font-mono font-bold text-2xl text-off-white mb-1">
            Terms of Service
          </h1>
          <p className="text-xs text-muted-ash font-mono">
            Last updated: April 2026 · Effective: April 2026
          </p>
        </div>

        <div className="space-y-8">
          <Section title="Acceptance">
            <p>
              By accessing sirt-five.vercel.app you agree to these terms. If you do not agree,
              please do not use the service.
            </p>
          </Section>

          <Section title="What S.I.R.T. Is">
            <p>
              S.I.R.T. (Security Incident Response Transcript) is a free, browser-based incident
              response checklist generator for security analysts and SOC teams. It produces
              procedural guidance based on user-provided configuration and publicly available
              security documentation.
            </p>
          </Section>

          <Section title="What S.I.R.T. Is Not">
            <ul className="space-y-1 font-mono text-xs">
              {[
                "An official security tool certified by any authority",
                "A substitute for qualified security professional judgment",
                "A SOAR platform, SIEM, or live security monitoring tool",
                "Affiliated with MITRE, any security vendor, or any regulatory body",
                "Responsible for the accuracy of LLM-generated output",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="text-signal-green shrink-0">·</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Checklists generated by S.I.R.T. are procedural guides only. All investigation
              decisions, escalation decisions, and incident conclusions are the sole responsibility
              of the analyst using the tool. S.I.R.T. does not make security determinations on
              your behalf.
            </p>
          </Section>

          <Section title="MITRE ATT&CK">
            <p>
              S.I.R.T. references the MITRE ATT&amp;CK® framework. MITRE ATT&amp;CK is a
              registered trademark of The MITRE Corporation. S.I.R.T. is not affiliated with or
              endorsed by MITRE.
            </p>
          </Section>

          <Section title="Your API Key & Data">
            <p>
              You are responsible for maintaining the security of your own LLM provider API key.
              S.I.R.T. processes your key and uploaded files as described in the Privacy Policy.
              Do not upload files containing classified, regulated, or highly sensitive personal
              data to S.I.R.T.
            </p>
          </Section>

          <Section title="Permitted Use">
            <p>
              S.I.R.T. is provided for professional and personal security operations use. You may
              not:
            </p>
            <ul className="space-y-1 font-mono text-xs">
              {[
                "Redistribute or resell access to S.I.R.T.",
                "Use S.I.R.T. to generate content for commercial security services without attribution",
                "Attempt to circumvent rate limiting or abuse the serverless API endpoints",
                "Use S.I.R.T. for any unlawful purpose",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="text-signal-green shrink-0">·</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </Section>

          <Section title="Intellectual Property">
            <p>
              S.I.R.T.&apos;s source code is published under the AGPL-3.0 License at{" "}
              <a
                href="https://github.com/mello-io/SIRT"
                target="_blank"
                rel="noopener noreferrer"
                className="text-signal-green hover:underline"
              >
                github.com/mello-io/SIRT
              </a>
              . The S.I.R.T. name and visual design are the property of the creator.
            </p>
            <p>
              Security tool names, product names, and trademarks referenced in S.I.R.T. are the
              property of their respective owners. S.I.R.T. is not affiliated with or endorsed by
              any security vendor referenced in the tool.
            </p>
          </Section>

          <Section title="Disclaimer of Warranties">
            <p>
              S.I.R.T. is provided &quot;as is&quot; without warranty of any kind. The creator
              makes no representations about the accuracy, completeness, or fitness for purpose of
              any checklist generated by the tool. LLM-generated content may contain errors.
              Always apply professional judgment.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              To the maximum extent permitted by law, the creator of S.I.R.T. shall not be liable
              for any direct, indirect, incidental, or consequential damages - including but not
              limited to security incidents, data breaches, or financial losses - arising from your
              use of or reliance on S.I.R.T. or its generated output.
            </p>
          </Section>

          <Section title="Changes to Terms">
            <p>
              These terms may be updated at any time. Continued use of S.I.R.T. after changes
              constitutes acceptance of the revised terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              <a
                href="https://github.com/mello-io/SIRT"
                target="_blank"
                rel="noopener noreferrer"
                className="text-signal-green hover:underline"
              >
                github.com/mello-io/SIRT
              </a>
            </p>
          </Section>
        </div>
      </div>
    </AppShell>
  );
}
